version: '3'

services:
  user_service:
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=user_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db_user
      - DB_PORT=5432
    volumes:
      - ./UserService:/usr/src/app
    depends_on:
      - db_user

  task_service:
    build:
      context: ./TaskService
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=task_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db_task
      - DB_PORT=5433
    volumes:
      - ./TaskService:/usr/src/app
    depends_on:
      - db_task

  notification_service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8002"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=notification_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db_notification
      - DB_PORT=5434
    volumes:
      - ./NotificationService:/usr/src/app
    depends_on:
      - db_notification

  db_user:
    image: postgres:12
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  db_task:
    image: postgres:12
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"

  db_notification:
    image: postgres:12
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5434"
