server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions/positions.yaml


clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'docker-logs'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
    pipeline_stages:
      - docker: {}
  - job_name: user_service_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: user_service
          __path__: /var/log/user_service/*.log